/**
 * src/lib/v1Migration.js — One-time production migration from MotoPark V1 to V2.
 *
 * WHY THIS EXISTS:
 * MotoPark V1 registered a PWA Service Worker via `vite-plugin-pwa` (Workbox) that
 * cached V1's HTML/JS/CSS in browser CacheStorage. Returning visitors would initially
 * be served V1 from their browser's SW cache.
 *
 * WHAT THIS DOES:
 * 1. Executes ONCE per user (controlled by `localStorage.getItem('mp_v1_sw_purged_v1')`).
 * 2. Unregisters all legacy Service Workers on this origin.
 * 3. Deletes ONLY V1-specific Workbox cache instances (workbox-*, api-*-cache, static-assets, etc.).
 * 4. Marks migration complete in localStorage so it never runs again.
 *
 * CAN BE SAFELY DELETED IN A FUTURE RELEASE once returning visitors have migrated.
 */

const MIGRATION_FLAG = 'mp_v1_sw_purged_v1';

// Exact & pattern-matched cache names generated by MotoPark V1's vite-plugin-pwa setup
const V1_CACHE_PATTERNS = [
  /^workbox-/i,
  /^api-(static|categories|products|dynamic)-cache$/i,
  /^static-assets$/i,
  /^cloudinary-images$/i,
  /^pwa-/i,
  /^mp-/i,
];

export async function purgeV1LegacyServiceWorker() {
  if (typeof window === 'undefined') return;

  // 1. One-time check: skip if already purged
  try {
    if (localStorage.getItem(MIGRATION_FLAG)) return;
  } catch {
    // Storage restricted (e.g. strict privacy mode) — proceed safely
  }

  try {
    // 2. Unregister legacy V1 Service Workers
    if ('serviceWorker' in navigator) {
      const registrations = await navigator.serviceWorker.getRegistrations();
      await Promise.all(registrations.map((reg) => reg.unregister()));
    }

    // 3. Delete ONLY V1 Workbox / PWA cache stores
    if ('caches' in window) {
      const cacheNames = await caches.keys();
      const v1CachesToDelete = cacheNames.filter((name) =>
        V1_CACHE_PATTERNS.some((pattern) => pattern.test(name))
      );
      await Promise.all(v1CachesToDelete.map((name) => caches.delete(name)));
    }

    // 4. Mark migration as complete so it runs only ONCE
    try {
      localStorage.setItem(MIGRATION_FLAG, 'true');
    } catch {
      // Ignore localStorage write failures
    }
  } catch (err) {
    console.warn('[V1 Migration] Legacy SW cleanup notice:', err?.message);
  }
}
